### ISSUE TITLE
[Bug] Incorrect Title Matching

### ISSUE THREAD

**Issue by GradyHooker** [nathanielw/humble-enhancer#3]
In the newest Humble Weekly Bundle, there is a game simply called "INK", but it matches the wrong game.

INK (Should Match) - http://store.steampowered.com/app/385710/
Steam Price - $6 NZ
Metacritic - 68

BRINK (Does Match) - http://store.steampowered.com/app/22350
Steam Price - $24 NZ
Metacritic - 70

**Comment by nathanielw** [comment]
Yeah, I think this is a bug at CheapShark's end - the only way I can get _INK_ to come up is to search by its Steam ID. I'll report it over on their tracker if you like.

Edit: https://bitbucket.org/ArmoredCavalry/cheapshark/issues/78/some-games-with-short-titles-dont-show-up
