### ISSUE TITLE
[Bug] Game Bounding Box Size

### ISSUE THREAD

**Issue by GradyHooker** [nathanielw/humble-enhancer#4]
For the newest Humble Weekly Bundle, they draw a bounding box around the next tier of games, but when this extension inserts the panel above it, it can push the normal Humble Bundle content out the bottom of this bounding box.

Here is an image of what I am talking about:
![image](https://cloud.githubusercontent.com/assets/4442335/13269311/f9f480ba-daeb-11e5-84a9-8d6bdda9c7c0.png)

**Comment by nathanielw** [comment]
Cheers, I noticed that too but completely forgot to look into it.
